### ISSUE TITLE
Control table ui

### ISSUE THREAD

**Issue by Amndeep7** [mitre/mitre-saf#76]
Todo:
- [x] Zebra striping for rows
  - Maybe have an extra highlight for the row+column that the mouse is hovering?
- [x] Pinstriping/borders for all cells
  - Thicker ones between the headers/frozen columns and the rest of the cells
- [x] Text wrapping on the column headers
- [x] Swap out 'true' for 'Inspec', 'SonarQ, ZAP, Burp' for the CWE one
- [x] Rename filters to "Control Row Filter" and "Assessment Column Filter"
- [x] [Change text on page to match Eugene's specs](https://github.com/mitre/mitre-saf/issues/76#issuecomment-631557727)
- [x] Use the full name of SonarQube
- [x] Implement interim solution for using unicode checkbox characters instead of icons
- [x] Format similar to the spreadsheet
- [x] File issue for the selection area against vuetify
  - [ ] File pr for that issue
- [x] File issue for using slots in at least the headers in the cheetah grid
  - [ ] File pr for that issue
- [x] File issue for headerRowHeight bug in the cheetah grid
  - [x] File pr for that issue
- [x] File issue for headers not re-rendering bug in the cheetah grid
  - [x] ~~File pr for that issue~~ Use recommended workaround
- [x] [Determine location to actually put the Control Table as opposed to in the header bar](https://github.com/mitre/mitre-saf/issues/76#issuecomment-631559451)
  - [x] [Place it in the FAQ](https://github.com/mitre/mitre-saf/issues/76#issuecomment-643483350)
  - [x] [Place it in the Validation page](https://github.com/mitre/mitre-saf/issues/76#issuecomment-643483350)
- [x] [Make table fit properly on the page](https://github.com/mitre/mitre-saf/issues/76#issuecomment-631833029)
  - [x] Reduce height of table
  - [x] Reduce vertical padding around the filters
- [x] [Checkmarks on dark mode are hard to see](https://github.com/mitre/mitre-saf/issues/76#issuecomment-631834774)
- [x] [Change 'all' to 'total assessment range'](https://github.com/mitre/mitre-saf/issues/76#issuecomment-631834774)
- [x] [Column filter adjustments](https://github.com/mitre/mitre-saf/issues/76#issuecomment-631839429)
  - [x] Global reset (use the checkbox in the nist controls column for this)
  - [x] Increase size of font for the checkbox
  - [x] Change background color for checkboxes that aren't 'x'
- [x] [Add 'Fortify' to the list for CWE](https://github.com/mitre/mitre-saf/issues/76#issuecomment-631848389)
- [x] [Change SonarQube back to SonarQ](https://github.com/mitre/mitre-saf/issues/76#issuecomment-631848389)
- [x] [Add legend below table + above footer for the tool names](https://github.com/mitre/mitre-saf/issues/76#issuecomment-631848389)
- [x] File issue against the vmware-vsphere-65-virtual-machine-stig-baseline repo for the duplicate directory
  - [x] File pr for that issue
- [x] Fix legend to add the control selector item (size of font for ballot box needs to be larger than the definition)
- [x] Reduce margins/padding even more
- [x] Change color scheme to have green for implemented controls, blue for the header - match up with what this [example](https://datatables.net/examples/styling/display.html) is doing more or less
- [x] [Fix themes not working right issue](https://github.com/mitre/mitre-saf/issues/76#issuecomment-645714778)

**Comment by Amndeep7** [comment]
Here is the pr for the vuetify issue: https://github.com/vuetifyjs/vuetify/issues/11434

**Comment by Amndeep7** [comment]
filter rename: https://github.com/mitre/mitre-saf/commit/8bb9240aed0d84d51f9e645ed5fbdd8ba5829085

**Comment by Amndeep7** [comment]
using words instead of true: https://github.com/mitre/mitre-saf/commit/0b7f5d06cc972de52a6969e6381467f693afe8d5

**Comment by ejaronne** [comment]
Change 

"SAF profiles are designed to cover NIST SP 800-53 Security Controls. See here to learn which profiles cover which controls." 

to

"All assessment tests under SAF are associated with NIST SP 800-53 Security Controls. Explore these associations in the table below!"

**Comment by ejaronne** [comment]
We still need to discuss where are how this Control Assessment Range table will be placed within the site. I know I don't want to crowd it on the home page. Let's discuss the correct placement. I think it should be a link placed at the top of the Validation page. I realize Validation Page needs to be more than just InSpec profiles. It should also list that which Heimdall_tools converts so that it is consistent with the table.

**Comment by wdower** [comment]
Added zebra stripes. Exact color scheme is up for debate but we can hot swap colors as needed now.

**Comment by Amndeep7** [comment]
https://github.com/future-architect/cheetah-grid/issues/244

Fixed a bug with the headerRowHeight property.  Need to wait until he approves the PR.  This is for the textwrapping task.

**Comment by Amndeep7** [comment]
Found I think another bug where if you have more than 2 header rows, it doesn't fully and properly invalidate and refresh the canvas on some sort of change until you scroll/hover over a different cell/etc.  Trying to make a reproducible case.

**Comment by Amndeep7** [comment]
Text wrapping: 8b6d77ac2aa25f7aad0249f2d1dbe477ca0f4ee2

**Comment by Amndeep7** [comment]
Marked the pinstriping as done cause the default behavior basically already implements it.

**Comment by ejaronne** [comment]
The header and filter sections take up too much vertical space, limiting the number of rows one can actually view at one time.
![image](https://user-images.githubusercontent.com/34140975/82514954-07f66d00-9ae5-11ea-9f9a-c002e29e1524.png)


In Chrome, at 100%, on a 16x9 aspect ratio monitor, *please* reduce the table height such that all rows are visible. If there are too many rows, I have to use the Chrome window vertical slider to see what is at the bottom of the page, but then I can't see the header information.
![image](https://user-images.githubusercontent.com/34140975/82515031-34aa8480-9ae5-11ea-9f2d-57115064bc13.png)

**Comment by ejaronne** [comment]
RE: the All column: 

Will pointed out that the "ALL" name is vague. It lists the total assessment range as filtered to the right, so... change "ALL to "Total Assessment Range"

Also, in dark mode, one can barely see the outline and fill of the checkboxes due to the blue color. Recommend white outline and white fill in dark (when checkmark) for visibility. black and black fill for light mode.

**Comment by ejaronne** [comment]
RE: blank, X, check box under headers:

Need a way to reset all columns back to X

When selecting checkbox toggles across several columns, it is difficult see which ones are x vs check vs blank. Highlight (yellow fill?) any column header that isn't set to X. And double the checkbox size, please.

Strange update behavior: when changing the checkbox for one column, the totals for columns to the left or right only update when you hover over them with cursor.

**Comment by ejaronne** [comment]
RE: Column widths, adjustments, and abbreviations

I'd prefer to fix the column widths to be similar to the spreadsheet I provided. The content should be visible based on my guidance below on column/row size: For the InSpec columns, I chose to have a clean consistent width based on the optimal wrapping across the headers. But for the CWE column, I had to choose a slightly wider column width *for just that one column*, to accommodate the wider **SonarQ, Fortify, ZAP, Burp** in the cell. (Note I forgot Fortify, please add as indicated.

btw, I abbreviated the names SonarQ, Fortify, ZAP, and Burp intentionally. But I didn't want to wrap the cells, nor did I want to abbreviate further. However, a Legend would be a nice addition, under the table, above the footer:

Legend:

- InSpec - (and our InSpec profiles) for assessing configuration settings, vulnerabilities, and least functionality
- SonarQ - SonarQube, open-source static code security analysis tool
- Fortify - HP Fortify, commercial static code security analysis tool
- ZAP - OWASP ZAP, open-source dynamic application security analysis tool
- Butp - Burp Suite Pro, commercial dynamic application security analysis tool

**Comment by ejaronne** [comment]
Re: Determine location to actually put the Control Table as opposed to in the header bar
- Remove the Control Assessment Range button from the top menu
- On the Validation Page, add this sentence: "All assessment tests under SAF are associated with NIST SP 800-53 Security Controls. Explore these associations in this [Control Assessment Range table](https://saf.mitre.org/#/control-table)!"
- On the FAQ page, add an FAQ to the top of the list "How many NIST SP 800-53 Security Controls are assessed under the SAF?", with the answer as: "Currently, about 162 NIST SP 800-53 security controls are assessed under this framework. Note that assessment coverage varies based on the component type. For more information, explore this [Control Assessment Range table](https://saf.mitre.org/#/control-table)!"

**Comment by ejaronne** [comment]
Odd - I'm getting inconsistent light/dark variations when I toggle darktolight, lighttodark. (using Chrome on Windows, Android.
![image](https://user-images.githubusercontent.com/34140975/84967286-9ad4f800-b0e1-11ea-99ed-49ec672b0ff3.png)
![image](https://user-images.githubusercontent.com/34140975/84967311-a6282380-b0e1-11ea-91f5-c768c7de8e1a.png)
![image](https://user-images.githubusercontent.com/34140975/84967326-ae805e80-b0e1-11ea-97bd-cd226baa6d1f.png)
![image](https://user-images.githubusercontent.com/34140975/84967338-b6d89980-b0e1-11ea-87ed-71fab2ef7058.png)

**Comment by Amndeep7** [comment]
@ejaronne yeah it registers the change once, but doesn't on repeat clicks.  I need to go through the commits to see when it stopped working on repeat clicks cause I'm fairly sure it used to work just fine.  Will probably also have to look through the library's code as well.

**Comment by Amndeep7** [comment]
This is completed except for us causing the linter to crash due to a bug it has.  The bug is resolved in the master branch, but there isn't a release out yet that includes it.  I've filed an issue asking for them to make a release here: https://github.com/vuejs/eslint-plugin-vue/issues/1221
